# https://github.com/nleiva/ee-builds/blob/master/ee-network-image/requirements.yml
collections:
  - name: community.general
    version: 5.0.0
  - name: cisco.ios
    version: 3.0.0
  - name: cisco.nxos
    version: 3.0.0
  - name: cisco.iosxr
    version: 3.0.0
  - name: ansible.netcommon
    version: 3.0.0
