- name: Gather facts
  hosts: routers
  gather_facts: false

  tasks:
    - name: Gather all network resource and minimal legacy facts [Cisco IOS]
      cisco.ios.ios_facts:
        gather_subset: min
        gather_network_resources: all
      when: ansible_network_os == 'cisco.ios.ios'

    - name: Gather all network resource and minimal legacy facts [Cisco NX-OS]
      cisco.nxos.nxos_facts:
        gather_subset: min
        gather_network_resources: all
      when: ansible_network_os == 'cisco.nxos.nxos'

    - name: Gather all network resource and minimal legacy facts [Cisco IOS XR]
      cisco.iosxr.iosxr_facts:
        gather_subset: min
        gather_network_resources: all
      when: ansible_network_os == 'cisco.iosxr.iosxr'
