- name: Configure User
  hosts: routers
  gather_facts: true
  vars_files: user.cfg

  tasks:
    - name: Use User resource module [Cisco IOS]
      cisco.ios.ios_user:
        name: "{{ cfg.user }}"
        configured_password: "{{ cfg.password }}"
        state: present
      when: ansible_network_os == 'cisco.ios.ios'

    - name: Use User resource module [Cisco NX-OS]
      cisco.nxos.nxos_user:
        name: "{{ cfg.user }}"
        configured_password: "{{ cfg.password }}"
        state: present
      when: ansible_network_os == 'cisco.nxos.nxos'

    - name: Use User resource module [Cisco IOS XR]
      cisco.iosxr.iosxr_user:
        name: "{{ cfg.user }}"
        configured_password: "{{ cfg.password }}"
        state: present
      when: ansible_network_os == 'cisco.iosxr.iosxr'
